CREATE TABLE app_users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,

    CONSTRAINT uk_app_users_email UNIQUE (email)
);

CREATE TABLE courses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT       NOT NULL,
    name        VARCHAR(150) NOT NULL,
    description TEXT,
    color       VARCHAR(20),
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_courses_owner
        FOREIGN KEY (owner_id)
            REFERENCES app_users (id)
            ON DELETE CASCADE
);

CREATE INDEX idx_courses_owner_id
    ON courses (owner_id);

CREATE TABLE topics
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id        BIGINT       NOT NULL,
    title            VARCHAR(200) NOT NULL,
    description      TEXT,
    display_position INTEGER,
    status           VARCHAR(30)  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_topics_course
        FOREIGN KEY (course_id)
            REFERENCES courses (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_topics_status
        CHECK (
            status IN (
                       'NOT_STARTED',
                       'LEARNING',
                       'REVIEWING',
                       'CONFIDENT'
                )
            )
);

CREATE INDEX idx_topics_course_id
    ON topics (course_id);

CREATE TABLE documents
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id          BIGINT       NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename   VARCHAR(255) NOT NULL,
    storage_path      VARCHAR(500) NOT NULL,
    mime_type         VARCHAR(100) NOT NULL,
    file_size         BIGINT       NOT NULL,
    page_count        INTEGER,
    processing_status VARCHAR(30)  NOT NULL,
    uploaded_at       TIMESTAMPTZ  NOT NULL,
    processed_at      TIMESTAMPTZ,

    CONSTRAINT uk_documents_topic_id UNIQUE (topic_id),

    CONSTRAINT fk_documents_topic
        FOREIGN KEY (topic_id)
            REFERENCES topics (id)
            ON DELETE CASCADE,

    CONSTRAINT chk_documents_processing_status
        CHECK (
            processing_status IN (
                                  'UPLOADED',
                                  'PROCESSING',
                                  'READY',
                                  'FAILED'
                )
            ),

    CONSTRAINT chk_documents_file_size
        CHECK (file_size >= 0),

    CONSTRAINT chk_documents_page_count
        CHECK (page_count IS NULL OR page_count >= 0)
);