CREATE TABLE document_chunks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT      NOT NULL,
    page_number INTEGER     NOT NULL,
    chunk_index INTEGER     NOT NULL,
    content     TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_document_chunks_document
        FOREIGN KEY (document_id)
            REFERENCES documents (id)
            ON DELETE CASCADE,

    CONSTRAINT uk_document_chunks_position
        UNIQUE (document_id, page_number, chunk_index),

    CONSTRAINT chk_document_chunks_page_number
        CHECK (page_number > 0),

    CONSTRAINT chk_document_chunks_index
        CHECK (chunk_index >= 0),

    CONSTRAINT chk_document_chunks_content
        CHECK (length(content) > 0)
);

CREATE INDEX idx_document_chunks_document_id
    ON document_chunks (document_id);

CREATE INDEX idx_document_chunks_page
    ON document_chunks (document_id, page_number);